import os

env = Environment()

debug = ARGUMENTS.get('debug', 0)

if int(debug):
	env.Append(CCFLAGS = '-g')

Export('env')

objs = []

objs = objs + SConscript('SConscript')

env.Library('cryptoc',objs)

